### ISSUE TITLE
Setting maxTimeout in SimpleDDP options causes loginResumeFailed event

### ISSUE THREAD

**Issue by fixmaker** [Gregivy/simpleddp-plugin-login#3]
### Description
If a value is set for `maxTimeout` in the options of the simpleDDP server, then the plugin will emit a `loginResumeFailed` event before the server reconnects.

### Steps To Reproduce
1. Use the following code snippet:
    ```
    import SimpleDDP from 'simpleDDP';
    import { simpleDDPLogin } from 'simpleddp-login-plugin';
    
    const opts = {
        endpoint: "ws://someserver.com/websocket",
        SocketConstructor: WebSocket,
        reconnectInterval: 5000,
        maxTimeout: 5000,
    };
    const server = new SimpleDDP(opts, [simpleDDPLogin]);
    
    server.on('loginResumeFailed', () => console.warn('Failed to re-login to the server'));
    
    server.login({ password: 'secret', { username: 'foo' } });
    ```
2. Force a server disconnect.

#### Observed Behaviour
The "Failed to re-login to the server" message is shown 5 seconds after the server disconnection (before the server reconnects).

#### Expected Behaviour
The plugin should wait until the server is reconnected, and then attempt to resume the login. If the login call times out (after 5 seconds) then the "Failed to re-login to the server" message is displayed.

### Comments
I am trying this using React Native (version 0.59).

I think the problem is that the login method is called as soon as the server disconnects, rather than waiting for the reconnected event.

**Comment by Gregivy** [comment]
Hello! What versions do you use (simpleddp and simpleddp-plugin-login)?

**Comment by fixmaker** [comment]
Hi. I installed the following versions from npm:

- simpleddp: 2.2.4
- simpleddp-plugin-login: 4.0.1

If it helps, I've been experimenting with the attached patch, which seems to solve the problem.

[simpleddp-plugin-login+4.0.1.patch.txt](https://github.com/Gregivy/simpleddp-plugin-login/files/3566387/simpleddp-plugin-login%2B4.0.1.patch.txt)

**Comment by Gregivy** [comment]
Thank you @fixmaker , I have not noticed such behaviour. I was able to reproduce and fix it. You can update the plugin, new version (4.0.2) is deployed to npm. Feel free to reopen if you face the same problem.
