### ISSUE TITLE
error when bundling the js file

### ISSUE THREAD

**Issue by smartgamer** [Gregivy/simpleddp-plugin-login#5]
Hi,
When I tried to bundle the js file using browserify, :
let userAuth = await server.login({
  password,
  user: {
    username,
  },
});

I got an error message: SyntaxError: Unexpected token. This error happens at "await". If I remove "await", it seems work fine. Do you know what's the issue and how to solve this?

Thanks,

**Comment by Gregivy** [comment]
Hello @smartgamer.
First of all your environment have to support `async/await` if not you should use babel + browserify to transpile `async/await` into a `promise` (also don`t forget to use `await` keyword only inside `async` functions). Either you can use promise `.then()` method but your environment have to support promises anyway, if promises are not supported you can use babel or include pollyfills for promises yourself.

Example with `.then()`:
```js
let userAuth;
server.login({
  password,
  user: {
    username,
  },
}).then(function(token) {userAuth = token});
```

**Comment by smartgamer** [comment]
> Hello @smartgamer.
> First of all your environment have to support `async/await` if not you should use babel + browserify to transpile `async/await` into a `promise` (also don`t forget to use `await`keyword only inside`async`functions). Either you can use promise`.then()` method but your environment have to support promises anyway, if promises are not supported you can use babel or include pollyfills for promises yourself.
> 
> Example with `.then()`:
> 
> ```js
> let userAuth;
> server.login({
>   password,
>   user: {
>     username,
>   },
> }).then(function(token) {userAuth = token});
> ```

**Comment by smartgamer** [comment]
@Gregivy Thank you for your reply. It's solved now. I didn't know await has to be inside async.
