### ISSUE TITLE
login with email is not working

### ISSUE THREAD

**Issue by smartgamer** [Gregivy/simpleddp-plugin-login#7]
Hi,

When I try to use login with email, it failed. Login only works when using username only.

let userAuth = await server.login({
password,
user: {
username,
email
}
});

any fix for this?

**Comment by Gregivy** [comment]
If you want to login with email your Meteor backend should support it first of all and then you can auth via simpleddp like this:
```js
await server.login({
  password: 'yourpassword',
  user: {
    email:'some@email.com' 
  }
});
```
I have made a test and it works.

**Comment by smartgamer** [comment]
Thank you!
